name: usgs_earthquake_analysis
channels:
  - defaults
dependencies:
  - contextily=1.5.0
  - geojson=3.1.0
  - geopandas=0.14.3
  - imageio=2.34.0
  - make=4.3
  - pandas=2.2.0
  - pyarrow=15.0.0
  - python=3.11
  - requests=2.31.0
